### ISSUE TITLE
написать тест bitonic array

### ISSUE THREAD

**Issue by seralekseenko** [someOaks/Algorithms#12]
- [x] Массив полностью убывающий;
- [x] Массив полностью возрастающий;
- [x] Массив рандомный большой с самым большим числом по центру ровно;
- [ ] Возможно сгенерить несколько больших рандомных массивов с рандомным расположением пикового значения в массиве! (но пока не уверен, что так стоит замарачиваться.

**Search in a bitonic array.** 

An array is bitonic if it is comprised of an increasing sequence of integers followed immediately by a decreasing sequence of integers. Write a program that, given a bitonic array of n distinct integer values, determines whether a given integer is in the array.

    Standard version: Use ∼3lg⁡n\sim 3 \lg n∼3lgn compares in the worst case.
    Signing bonus: Use ∼2lg⁡n\sim 2 \lg n∼2lgn compares in the worst case (and prove that no algorithm can guarantee to perform fewer than ∼2lg⁡n\sim 2 \lg n∼2lgn compares in the worst case).

**Comment by seralekseenko** [comment]
Необходимо дать тесту возможность запускать тестируемый код как с использованием массива из тестового файла так и с использованием массива введенного вручную в коде.

**Comment by Glebuar** [comment]
Write a bitonic array test.
